/**
 * Export utilities for LexGuard report generation.
 */
import type { AnalysisResponse, RiskAnalysis } from '../api';

const SEV_EMOJI: Record<string, string> = {
  CRITICAL: '🔴', HIGH: '🟠', MEDIUM: '🟡', LOW: '🟢', NONE: '⚪',
};

export function generateTextReport(analysis: AnalysisResponse): string {
  const { filename, risk_summary: rs, clauses, risk_analyses } = analysis;
  const now = new Date().toLocaleString();
  const riskMap = new Map<string, RiskAnalysis>(risk_analyses.map(r => [r.clause_id, r]));

  const lines: string[] = [];
  const divider = '═'.repeat(72);
  const section = '─'.repeat(72);

  lines.push(divider);
  lines.push('  LEXGUARD — AI CONTRACT INTELLIGENCE REPORT');
  lines.push(divider);
  lines.push(`  Document : ${filename}`);
  lines.push(`  Generated: ${now}`);
  lines.push('');

  if (rs) {
    lines.push(divider);
    lines.push('  EXECUTIVE SUMMARY');
    lines.push(divider);
    lines.push(`  Overall Risk Score : ${Math.round(rs.overall_score)}/100`);
    lines.push(`  Severity Level     : ${SEV_EMOJI[rs.severity_level] ?? ''} ${rs.severity_level}`);
    lines.push(`  Recommendation     : ${rs.signing_recommendation}`);
    lines.push(`  Total Clauses      : ${rs.total_clauses}`);
    lines.push(`  ├─ Critical        : ${rs.critical_count}`);
    lines.push(`  ├─ High            : ${rs.high_count}`);
    lines.push(`  ├─ Medium          : ${rs.medium_count}`);
    lines.push(`  └─ Low             : ${rs.low_count}`);
    lines.push(`  Processing Time    : ${rs.processing_time?.toFixed(1) ?? 0}s`);
    lines.push('');

    if (rs.key_findings.length > 0) {
      lines.push('  KEY FINDINGS');
      lines.push(section);
      rs.key_findings.forEach((f: string, i: number) => lines.push(`  ${i + 1}. ${f}`));
      lines.push('');
    }

    if (Object.keys(rs.risk_by_category).length > 0) {
      lines.push('  RISK BY CATEGORY');
      lines.push(section);
      Object.entries(rs.risk_by_category).forEach(([cat, count]) => {
        lines.push(`  ${cat.replace(/_/g, ' ').padEnd(30)} ${count} clause${count !== 1 ? 's' : ''}`);
      });
      lines.push('');
    }
  }

  // Sort clauses by severity descending
  const sorted = [...clauses].sort((a, b) => {
    const sa = (riskMap.get(a.id)?.severity_score) ?? 0;
    const sb = (riskMap.get(b.id)?.severity_score) ?? 0;
    return sb - sa;
  });

  if (sorted.length > 0) {
    lines.push(divider);
    lines.push('  CLAUSE ANALYSIS');
    lines.push(divider);

    sorted.forEach((clause, idx) => {
      const risk = riskMap.get(clause.id);
      const sev = risk?.severity_level ?? 'UNKNOWN';
      const score = risk?.severity_score?.toFixed(1) ?? '—';
      const emoji = SEV_EMOJI[sev] ?? '⚪';

      lines.push('');
      lines.push(`  ${idx + 1}. [${clause.section_reference || clause.id}]  ${clause.type.replace(/_/g, ' ')}`);
      lines.push(`     ${emoji} ${sev} RISK — Score: ${score}/10`);
      lines.push('');
      lines.push('     CLAUSE TEXT:');
      // Word-wrap at 70 chars
      const words = clause.text.split(' ');
      let line = '     ';
      words.forEach((word: string) => {
        if ((line + word).length > 72) {
          lines.push(line.trimEnd());
          line = '     ' + word + ' ';
        } else {
          line += word + ' ';
        }
      });
      if (line.trim()) lines.push(line.trimEnd());

      if (risk) {
        lines.push('');
        lines.push('     RISK ANALYSIS:');
        lines.push(`     ${risk.severity_reasoning}`);
        if (risk.legal_exposure) {
          lines.push('');
          lines.push('     LEGAL EXPOSURE:');
          lines.push(`     ${risk.legal_exposure}`);
        }
        if (risk.recommendations && risk.recommendations.length > 0) {
          lines.push('');
          lines.push('     RECOMMENDATIONS:');
          risk.recommendations.slice(0, 3).forEach((r) => {
            lines.push(`     \u2192 ${r.action}`);
            if (r.suggested_language) {
              lines.push(`       Suggested: "${r.suggested_language}"`);
            }
          });
        }
      }
      lines.push('');
      lines.push('  ' + section.slice(2));
    });
  }

  lines.push('');
  lines.push(divider);
  lines.push('  DISCLAIMER');
  lines.push(divider);
  lines.push('  This report is generated by an AI system and is for informational');
  lines.push('  purposes only. It does not constitute legal advice. Consult a');
  lines.push('  qualified solicitor before making decisions based on this analysis.');
  lines.push(divider);

  return lines.join('\n');
}

export function downloadReport(analysis: AnalysisResponse): void {
  const text = generateTextReport(analysis);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const safeName = (analysis.filename || 'contract').replace(/[^a-z0-9]/gi, '_');
  a.href = url;
  a.download = `LexGuard_Report_${safeName}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
